version: '3'

services:
  customer-app:
    container_name: customer-app
    build:
      context: .docker
      dockerfile: Dockerfile
    image: customer-app
    depends_on:
      - customer-db
    environment:
      APP_URL: "${APP_URL}"
      APP_ENV: "${APP_ENV}"
    volumes:
      - ./:/app:cached
    env_file:
      - .env
    expose:
      - 9001

  customer-nginx:
    container_name: customer-nginx
    image: nginx:alpine
    ports:
      - "${APP_PORT}:80"
    volumes:
      - .docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf:cached
      - ./:/app:cached
      - .docker/nginx/:/var/log/nginx/
    depends_on:
      - customer-app
      - customer-db
    links:
      - customer-db
    env_file:
      - .env

  customer-db:
    container_name: customer-db
    image: mariadb:latest
    ports:
      - "8902:3006"
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD}
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    restart: on-failure
    volumes:
      - customer-db-volume:/var/lib/mysql
      - .docker/db/dump.sql:/docker-entrypoint-initdb.d/dump.sql


volumes:
  customer-db-volume:
